# Numpy Introduction

In [1]:
import numpy as np

### Creating arrays

In [2]:
L = [1,2,3,4]
np.array(L)

array([1, 2, 3, 4])

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# arange(start, stop) returns a numpy array
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [5]:
# arange(start, stop, step_size) returns a numpy array
np.arange(4,10,2)

array([4, 6, 8])

In [6]:
# multidimensional array
array_of_arrays = [[1,2,3], [4,5,6], [7,8,9]]
np.array(array_of_arrays)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# reshape(n_rows, n_columns) changes the shape of a numpy array

np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Useful methods

In [8]:
arr = np.array([17, 9, 3, -5, -1])

In [9]:
arr.max()

17

In [10]:
arr.min()

-5

In [11]:
arr.mean()

4.6

In [12]:
arr.std()

7.735631842325487

In [13]:
arr.sort()

In [14]:
arr

array([-5, -1,  3,  9, 17])

In [15]:
X = np.arange(1, 26).reshape(5,5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
# to Flatten a numpy array
#X.ravel()
X.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

### Array indexing

In [17]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[8]

8

In [19]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [20]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
arr[-1]

9

In [22]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Element-wise operations

In [23]:
# python List
L = [1,2,3,4,5]

# numpy array
arr = np.array([1,2,3,4,5])

In [24]:
L*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [25]:
arr*2

array([ 2,  4,  6,  8, 10])

In [26]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5])

### Universal functions

In [27]:
arr_by5 = np.array([15,5,20,10])
arr_by5

array([15,  5, 20, 10])

In [28]:
np.min(arr_by5)

5

In [29]:
# index position of the smallest value
np.argmin(arr_by5)

1

In [30]:
np.max(arr_by5)

20

In [31]:
# index position of the largest value
np.argmax(arr_by5)

2

In [32]:
# index position of the smallest to the largest values
np.argsort(arr_by5)

array([1, 3, 0, 2], dtype=int64)